site_name: Bazarr Wiki
site_description: Wiki for Bazarr, Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
site_author: TRaSH
site_url: http://wiki.bazarr.media/

repo_url: https://github.com/bazarr/wiki
repo_name: bazarr/wiki

copyright: Copyright &copy; 2021 Bazarr

extra:
  analytics:
    provider: google
    property: G-SCTEHY8EX0
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/discord
      link: http://wiki.bazarr.media/discord
    - icon: fontawesome/brands/square-github
      link: https://github.com/morpheus65535/bazarr

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - lightgallery

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      locale: en
  - awesome-pages
  - redirects:
      redirect_maps:
        discord.md: https://discord.gg/MH2e2eb
        FAQ.md: Troubleshooting/FAQ.md
        Help.md: Troubleshooting/Asking-for-help-or-report-a-problem.md
        Logs.md: Troubleshooting/Logging-and-Log-Files.md
        Setup-Guide.md: Getting-Started/Setup-Guide.md
        Installation.md: Getting-Started/Installation/index.md
        Cloud.md: Additional-Configuration/Performance-Tuning.md
        stats.md: bazarr-stats.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigio
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"
  favicon: img/favicon.png
  logo: img/logo.png
